summary: "Create Category"
description: ""
consumes:
- "aplication/json"
produces:
- "aplication/json"
parameters:
- in: "body"
  name: "body"
  description: "field body"
  required: true
  schema: 
    type: "object"
    properties:

      category_name:
        type: "string"
        format: "object"
        example: "Shoe"
     
responses:
  404:
    description: "category_created_not_found"
