summary: "Create User"
description: ""
consumes:
- "aplication/json"
produces:
- "aplication/json"
parameters:
- in: "body"
  name: "body"
  description: "field body"
  required: true
  schema: 
    type: "object"
    properties:
      email:
        type: "string"
        format: "object"
        example: "@.com"

      first_name:
        type: "string"
        format: "object"
        example: "Fred"

      last_name:
        type: "string"
        format: "object"
        example: "Santos"

      contact_number:
        type: "string"
        format: "object"
        example: "11X9999-9999"

      password:
        type: "string"
        format: "object"
        example: "123456"

      role:
        type: "string"
        format: "object"
        example: "SUPPLIER or CUSTOMER"
     
responses:
  404:
    description: "user_created_not_found"
